"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, token } from "@/lib/api";

type Product = { _id: string; name: string };
type Watch = { _id: string; thumbnailLink?: string; thumbnailUrl?: string; videoLink?: string; videoUrl?: string; productId?: string | Product };
type Instagram = { _id: string; coverImageUrl: string; videoUrl?: string; instaLink: string };

export default function AdminContentManager() {
  const [products, setProducts] = useState<Product[]>([]), [watch, setWatch] = useState<Watch[]>([]), [instagram, setInstagram] = useState<Instagram[]>([]), [message, setMessage] = useState("");
  const [watchForm, setWatchForm] = useState({ thumbnailLink: "", videoLink: "", productId: "" }); const [instaForm, setInstaForm] = useState({ coverImageUrl: "", videoUrl: "", instaLink: "" });
  const load = async () => { try { const [productsData, watchData, instagramData] = await Promise.all([api<{ products: Product[] }>("/api/products?limit=100"), api<{ items: Watch[] }>("/api/content/watch-and-buy"), api<{ posts: Instagram[] }>("/api/content/instagram")]); setProducts(productsData.products); setWatch(watchData.items); setInstagram(instagramData.posts); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not load content."); } };
  useEffect(() => { load(); }, []);
  async function saveWatch(event: FormEvent) { event.preventDefault(); try { await api("/api/content/watch-and-buy", { method:"POST", token:token(), body:JSON.stringify(watchForm) }); setWatchForm({ thumbnailLink:"", videoLink:"", productId:"" }); setMessage("Watch & Buy item saved."); load(); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not save Watch & Buy item."); } }
  async function saveInstagram(event: FormEvent) { event.preventDefault(); try { await api("/api/content/instagram", { method:"POST", token:token(), body:JSON.stringify(instaForm) }); setInstaForm({ coverImageUrl:"", videoUrl:"", instaLink:"" }); setMessage("Instagram post saved."); load(); } catch (err) { setMessage(err instanceof Error ? err.message : "Could not save Instagram post."); } }
  async function remove(path: string) { await api(path, { method:"DELETE", token:token() }); load(); }
  return <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-[#ebe3da] bg-white p-6"><h2 className="font-serif text-2xl">Watch & Buy</h2><p className="mt-2 text-sm text-[#806f63]">Add a thumbnail, video link, and the perfume to show alongside it.</p><form onSubmit={saveWatch} className="mt-5 space-y-3"><Field label="Thumbnail link" value={watchForm.thumbnailLink} set={(value) => setWatchForm({ ...watchForm, thumbnailLink:value })} /><Field label="Video link" value={watchForm.videoLink} set={(value) => setWatchForm({ ...watchForm, videoLink:value })} /><select required value={watchForm.productId} onChange={(e) => setWatchForm({ ...watchForm, productId:e.target.value })} className="w-full rounded-lg border border-[#e3d9cf] p-3 text-sm"><option value="">Select perfume</option>{products.map((product) => <option key={product._id} value={product._id}>{product.name}</option>)}</select><button className="w-full rounded-xl bg-[#312820] py-3 text-sm text-white">Add Watch & Buy</button></form><div className="mt-6 space-y-2">{watch.map((item) => <div key={item._id} className="flex items-center justify-between rounded-lg bg-[#f7f2ec] p-3 text-sm"><span>{typeof item.productId === "object" ? item.productId.name : "Watch item"}</span><button onClick={() => remove(`/api/content/watch-and-buy/${item._id}`)} className="text-[#9a5d4f]">Remove</button></div>)}</div></div><div className="rounded-2xl border border-[#ebe3da] bg-white p-6"><h2 className="font-serif text-2xl">Instagram</h2><p className="mt-2 text-sm text-[#806f63]">Upload each post’s cover, optional reel video, and Instagram post link.</p><form onSubmit={saveInstagram} className="mt-5 space-y-3"><Field label="Cover image link" value={instaForm.coverImageUrl} set={(value) => setInstaForm({ ...instaForm, coverImageUrl:value })} /><Field label="Video link (optional)" value={instaForm.videoUrl} set={(value) => setInstaForm({ ...instaForm, videoUrl:value })} /><Field label="Instagram post / reel link" value={instaForm.instaLink} set={(value) => setInstaForm({ ...instaForm, instaLink:value })} /><button className="w-full rounded-xl bg-[#312820] py-3 text-sm text-white">Add Instagram post</button></form><div className="mt-6 grid grid-cols-3 gap-2">{instagram.map((post) => <div key={post._id} className="relative aspect-square overflow-hidden rounded-lg bg-[#f7f2ec]"><img src={post.coverImageUrl} alt="Instagram post" className="h-full w-full object-cover" /><button onClick={() => remove(`/api/content/instagram/${post._id}`)} className="absolute bottom-1 left-1 rounded bg-white px-2 py-1 text-[10px] text-[#9a5d4f]">Remove</button></div>)}</div></div>{message && <p className="text-sm text-[#705846] xl:col-span-2">{message}</p>}</section>;
}
function Field({ label, value, set }: { label:string; value:string; set:(value:string)=>void }) { return <label className="block text-xs text-[#796b60]">{label}<input required={label !== "Video link (optional)"} value={value} onChange={(e) => set(e.target.value)} className="mt-1 w-full rounded-lg border border-[#e3d9cf] p-3 text-sm" /></label>; }
