"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { useCart } from "@/components/context/CartContext";

type Product = { _id: string; name: string; brand?: string; description?: string; price: number; images?: string[]; coverImage?: string };
type Watch = { _id: string; title?: string; thumbnailLink?: string; videoLink: string; product?: Product };
type Pack = { _id: string; name: string; description?: string; price: number; image?: string; bottleCount?: number };
const img = (product?: Product) => product?.coverImage || product?.images?.[0] || "";

export default function StorefrontSections() {
  const { addToCart } = useCart(); const [featured, setFeatured] = useState<Product[]>([]), [watch, setWatch] = useState<Watch[]>([]), [packs, setPacks] = useState<Pack[]>([]);
  useEffect(() => { api<{ products: Product[] }>("/api/products?featured=true&limit=12").then((r) => setFeatured(r.products)).catch(() => undefined); api<{ items: Watch[] }>("/api/content/watch-and-buy").then((r) => setWatch(r.items)).catch(() => undefined); api<{ packs: Pack[] }>("/api/discovery-packs").then((r) => setPacks(r.packs)).catch(() => undefined); }, []);
  return <>
    {watch.length > 0 && <section className="bg-[#1f2622] px-5 py-20 text-[#fffaf3] md:px-10"><div className="mx-auto max-w-7xl"><p className="text-center text-[10px] font-bold tracking-[.3em] text-[#e3bd91]">WATCH & BUY</p><h2 className="mt-3 text-center font-serif text-4xl">See the scent in motion.</h2><div className="mt-10 flex snap-x gap-5 overflow-x-auto pb-4">{watch.map((item) => <article key={item._id} className="min-w-[82%] snap-center sm:min-w-[45%] lg:min-w-[31%]"><div className="aspect-[4/5] overflow-hidden rounded-2xl bg-[#2a362f]">{item.thumbnailLink ? <img src={item.thumbnailLink} alt={item.title || item.product?.name || "Darnera scent"} className="h-full w-full object-cover" /> : <video src={item.videoLink} controls muted playsInline className="h-full w-full object-cover" />}</div><h3 className="mt-4 font-serif text-2xl">{item.title || item.product?.name}</h3>{item.product && <button onClick={() => addToCart({ id: item.product!._id, name: item.product!.name, subtitle: item.product!.brand || "DARNERA", price: item.product!.price, image: img(item.product) })} className="mt-3 rounded-full border border-white/30 px-4 py-2 text-xs">ADD TO BAG · ₹ {item.product.price.toLocaleString()}</button>}</article>)}</div></div></section>}
    {featured.length > 0 && <section className="bg-[#faf7f2] px-5 py-20 md:px-10"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="text-[10px] font-semibold tracking-[.28em] text-[#b88962]">CURATED BY DARNERA</p><h2 className="mt-3 font-serif text-4xl">Featured collection</h2></div><Link href="/collection" className="text-sm text-[#8c684f]">Explore all →</Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{featured.map((product) => <article key={product._id} className="overflow-hidden rounded-2xl bg-white shadow-sm"><Link href={`/product/${product._id}`} className="block aspect-[4/5] bg-[#eee7df]">{img(product) && <img src={img(product)} alt={product.name} className="h-full w-full object-contain p-5" />}</Link><div className="p-5"><p className="text-[10px] tracking-[.18em] text-[#a47b60]">{product.brand || "DARNERA"}</p><h3 className="mt-2 font-serif text-xl">{product.name}</h3><p className="mt-3 text-sm">₹ {product.price.toLocaleString()}</p><button onClick={() => addToCart({ id: product._id, name: product.name, subtitle: product.brand || "DARNERA", price: product.price, image: img(product) })} className="mt-4 rounded-full bg-[#312820] px-4 py-2 text-xs text-white">ADD TO BAG</button></div></article>)}</div></div></section>}
    {packs.length > 0 && <section className="bg-[#fffdfa] px-5 py-20 md:px-10"><div className="mx-auto max-w-7xl"><p className="text-[10px] font-bold tracking-[.3em] text-[#ad8265]">DISCOVERY PACKS</p><h2 className="mt-3 font-serif text-4xl">Small bottles, a wider world.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{packs.map((pack) => <article key={pack._id} className="overflow-hidden rounded-3xl bg-[#eee4d9]"><div className="aspect-[16/10]">{pack.image && <img src={pack.image} alt={pack.name} className="h-full w-full object-contain p-5" />}</div><div className="bg-white p-6"><p className="text-xs tracking-widest text-[#a47b60]">SET OF {pack.bottleCount || ""}</p><h3 className="mt-2 font-serif text-2xl">{pack.name}</h3><p className="mt-3 text-sm text-[#806f63]">{pack.description}</p><p className="mt-4 font-serif text-xl">₹ {pack.price.toLocaleString()}</p></div></article>)}</div></div></section>}
    <section className="overflow-hidden bg-[#f0e8df] py-20"><p className="text-center text-[10px] font-bold tracking-[.3em] text-[#a4795d]">FROM THE DARNERA CIRCLE</p><h2 className="mt-3 text-center font-serif text-4xl">Worn. Loved. Remembered.</h2><div className="mt-10 flex w-max animate-[marquee_42s_linear_infinite] gap-5 px-5">{["A scent that stays close, but never goes unnoticed.", "Beautifully made and memorable from the first spray.", "My new everyday ritual.", "Elegant, warm, and distinctly Darnera.", "A fragrance I keep returning to."].concat(["A scent that stays close, but never goes unnoticed.", "Beautifully made and memorable from the first spray.", "My new everyday ritual.", "Elegant, warm, and distinctly Darnera.", "A fragrance I keep returning to."]).map((text, index) => <article key={index} className="w-[320px] shrink-0 rounded-2xl bg-[#fffdfa] p-7 shadow-sm"><p className="text-sm tracking-[.2em] text-[#b17b57]">★★★★★</p><p className="mt-5 font-serif text-xl leading-8 text-[#49382d]">“{text}”</p><p className="mt-6 text-xs tracking-[.15em] text-[#907464]">VERIFIED REVIEW</p></article>)}</div></section>
  </>;
}
