"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useCart } from "@/components/context/CartContext";
import { api } from "@/lib/api";
type Product = { _id: string; name: string; brand?: string; category?: string; description?: string; price: number; stock: number; images?: string[]; productImages?: { url: string }[] };
export default function ProductPage() { const params = useParams<{ id: string }>(), { addToCart } = useCart(); const [product, setProduct] = useState<Product | null>(null), [error, setError] = useState(""); useEffect(() => { api<{ product: Product }>(`/api/products/${params.id}`).then((data) => setProduct(data.product)).catch((err) => setError(err.message)); }, [params.id]); if (error) return <main className="min-h-screen bg-[#fffdfa]"><Navbar /><p className="p-20 text-center text-red-700">{error}</p><Footer /></main>; if (!product) return <main className="min-h-screen bg-[#fffdfa]"><Navbar /><p className="p-20 text-center">Loading fragrance…</p><Footer /></main>; const images = product.images?.length ? product.images : product.productImages?.map((item) => item.url) || ["/perfume/eidolon.png"]; return <main className="min-h-screen bg-[#fffdfa]"><Navbar /><div className="mx-auto grid max-w-6xl gap-10 px-5 py-12 md:grid-cols-2 md:px-10"><div className="grid grid-cols-2 gap-4">{images.map((image, index) => <div key={`${image}-${index}`} className="aspect-square rounded-2xl bg-[#f2ebe3]"><img src={image} alt={product.name} className="h-full w-full object-contain p-6" /></div>)}</div><section className="md:pt-8"><Link href="/collection" className="text-xs text-[#926b50]">← Back to collection</Link><p className="mt-8 text-[10px] tracking-[.25em] text-[#a47b60]">{product.brand || product.category || "DARNERA"}</p><h1 className="mt-3 font-serif text-5xl">{product.name}</h1><p className="mt-5 text-sm leading-7 text-[#66584e]">{product.description || "A carefully composed Darnera fragrance."}</p><p className="mt-8 font-serif text-3xl">₹ {product.price.toLocaleString()}</p><p className={`mt-2 text-sm ${product.stock > 0 ? "text-[#55704f]" : "text-[#a05f55]"}`}>{product.stock > 0 ? `${product.stock} bottles available` : "Currently sold out"}</p><button disabled={!product.stock} onClick={() => addToCart({ id: product._id, name: product.name, subtitle: product.brand || product.category || "DARNERA", price: product.price, image: images[0] })} className="mt-8 w-full rounded-xl bg-[#342a22] py-4 text-xs font-semibold tracking-[.16em] text-white disabled:opacity-40">ADD TO BAG</button></section></div><Footer /></main>; }
